# Generated by Django 4.1.7 on 2023-03-25 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0002_remove_user_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
